[clog]
repository = "https://github.com/python-zk/kazoo"
changelog = "CHANGES.md"
from-latest-tag = true
link-style = "github"

[sections]
Refactor = ["refactor"]
Test = ["test"]
Doc = ["docs"]
Chore = ["chore"]
Features = ["feat", "feature"]
"Bug Fixes" = ["fix", "bug"]
