Server {
    com.sun.security.auth.module.Krb5LoginModule required
    debug=false
    isInitiator=false
    useKeyTab=true
    keyTab="/conf/server.keytab"
    storeKey=true
    useTicketCache=false
    principal="zookeeper/127.0.0.1@EXAMPLE.ORG";
};
